### ISSUE TITLE
SVG is sent despite options to not send it

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#12]
I remove the svg display options like this: 

```
old = getOption("jupyter.display_mimetypes")
options(jupyter.display_mimetypes = old[1:length(old)-1]) # the last element is svg
print(getOption("jupyter.display_mimetypes"))
[1] "text/plain"             "text/html"              "text/markdown"         
[4] "text/latex"             "application/json"       "application/javascript"
[7] "application/pdf"        "image/png"              "image/jpeg" 
```

But the notebook still contains svg and I can't right click on the image and save the image :-(

**Comment by jankatins** [comment]
Ah, it seems that I have to change `'jupyter.plot_mimetypes'`...

**Comment by jankatins** [comment]
Do we have a page where we list all the options?

**Comment by takluyver** [comment]
I don't think we do, but it's a good idea.

**Comment by flying-sheep** [comment]
we should simply host the docs created from the .Rd files via `Rd2HTML`, and host/link them from https://irkernel.github.io
