### ISSUE TITLE
Lots of whitespace around grid useage...

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#15]
Not sure where this comes from:

``` r
library(grid)
library(gridExtra)
d <- head(iris, 3)
g <- tableGrob(d)
grid.newpage()
grid.draw(g)
```

produces a plot which has lots of whitespace around it :-(

Happens with svg and svg removed

**Comment by flying-sheep** [comment]
that’s simply what grid does. it maintains it own aspect ratio and centers a box with that aspect ratio within the plot region.

at least i think it does

**Comment by jankatins** [comment]
Ok, in rstudio, there is also a wide gap around it :-(
