### ISSUE TITLE
Release on CRAN

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#20]
IMO no issues are important enough to not release...

I've also added a small PR https://github.com/IRkernel/IRdisplay/pull/21 to fix the one error, but after that (and installing base64enc from the git source... I do love the change in the compiler on win...) it's all good:

```
c:\data\external\R
λ build_rpackage.bat --Rdevel --check irdisplay
# Building packages: irdisplay
# Checking: yes
# Building for R-devel
c:\Program Files\R\R-devel
 - Building package irdisplay
* checking for file 'irdisplay/DESCRIPTION' ... OK
* preparing 'IRdisplay':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'IRdisplay_0.3.0.9000.tar.gz'

# CHECKING the package
* using log directory 'c:/data/external/R/IRdisplay.Rcheck'
* using R Under development (unstable) (2016-04-25 r70548)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'IRdisplay/DESCRIPTION' ... OK
* this is package 'IRdisplay' version '0.3.0.9000'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'IRdisplay' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... NONE
* checking PDF version of manual ... OK
* DONE

Status: OK

* installing to library 'C:/portabel/R/R/win-library/3.4'
* installing *source* package 'IRdisplay' ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* MD5 sums
packaged installation of 'IRdisplay' as IRdisplay_0.3.0.9000.zip
* DONE (IRdisplay)
c:\data\external\R

c:\data\external\R
λ
```

**Comment by jankatins** [comment]
Comments?

**Comment by jankatins** [comment]
Added automatic tests and cran comments in #22 

IMO the only thing would be to descide how https://github.com/IRkernel/IRkernel/issues/257#issuecomment-217618492

-> Make base_display a function in the `options()`, so that other packages can overwrite it easier (=without a `R CMD check` ERROR/NOTE)

**Comment by clayms** [comment]
I get the error:

```
Warning message:
package ‘IRdisplay’ is not available (for R version 3.2.5) 
```

**Comment by jankatins** [comment]
IRdisplay is not yet on CRAN, so you have to install that from source as well via `devtools::install_github("irkernel/IRdisplay")`.

**Comment by flying-sheep** [comment]
make that a forward slash and use proper capitalization, then it’ll work.

**Comment by jankatins** [comment]
I did that on my mobile :-) (updated above)

**Comment by jankatins** [comment]
IMO this is ready to release to CRAN. First this and then IRkernel 0.7?

**Comment by flying-sheep** [comment]
Sure! Although we need to think about this: people who have the old stuff installed and then run `update.packages` will only get the new IRdisplay, which is incompatible with the old IRkernel.

**Comment by jankatins** [comment]
You mean the new base_display stuff? AFAI understand it, an older irkernel is compatible with the new irdisplay: it would simply completely swap out the new function as irkernel did before. Only the reverse old irdiplay and new irkernel will fail.

**Comment by flying-sheep** [comment]
ah, good!

**Comment by flying-sheep** [comment]
submitted

**Comment by jankatins** [comment]
In my R3.3 environment, I get a problem in the DESCRIPTION: Title case and description is off. PR incoming...

**Comment by jankatins** [comment]
https://github.com/IRkernel/IRdisplay/pull/35/files

**Comment by flying-sheep** [comment]
hmm, weird, i didn’t (on arch 3.3.1 is the default R)

/e: [travis (even on devel) neither](https://travis-ci.org/IRkernel/IRdisplay/jobs/143004782#L606-L659). what exact R version and command line made you see the CHECK problem?

**Comment by flying-sheep** [comment]
Fixed: https://cran.r-project.org/web/packages/IRdisplay/

**Comment by takluyver** [comment]
Thanks!

**Comment by flying-sheep** [comment]
no problems. getting the license stuff right war pretty hard, as it’s documented nowhere, so you pretty much have to ask endless questions or search through CRAN until you find examples that are similar to your use case. other than that, smooth sailing. repr was online much faster due to being GPL.
