### ISSUE TITLE
Remove option jupyter.rich_display

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#30]
This option belongs to the kernel and is only kept here to be compatible with an older IRkernel, which expects it set. Remove it after both projects have a release.

**Comment by flying-sheep** [comment]
why? again: this is dev version. we can be nice by making the dev kernel depend on a certain IRdisplay dev version, but here be dragons.

i made master IRkernel depend on a new IRdisplay version in IRkernel/IRkernel@5a90ca66d64bd0c1df7d71f62a0dc6a8f4add54e

**Comment by jankatins** [comment]
Unfortunately IRkernel is already used in in production via the conda packages. So IMO we should be nice to these users/packagers by not coupling the package versions to tightly.

**Comment by flying-sheep** [comment]
as a packager, i know it’s my responsibility to make the packages in the repos work, including running tests.

they know that, too, and if they don’t do it, it’s their bug.
