### ISSUE TITLE
Error when running plot.ly commands

### ISSUE THREAD

**Issue by codingbutstillalive** [IRkernel/IRdisplay#38]
Hello!

I am trying to execute the following lines of codes (from here: https://plot.ly/ggplot2/), but then it yields an error message, saying: "**HTML widgets cannot be represented in plain text (need html)**". Why is this and how can this be fixed?

```r
require(ggplot2); require(plotly)

set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]

p <- ggplot(data = d, aes(x = carat, y = price)) +
geom_point(aes(text = paste("Clarity:", clarity)), size = 4) +
geom_smooth(aes(colour = cut, fill = cut)) + facet_wrap(~ cut)

(gg <- ggplotly(p))
```

**Comment by flying-sheep** [comment]
That's the plain text representation of a htmlwidget.

ggplotly (or its print method) seems to return one.

What classes does the object returned by ggplotly have? What print function is dispatched on it?

**Comment by codingbutstillalive** [comment]
Well, ggplotly returns an html widget, as far as I can see. I probably links to the function `plotly:::ggplotly.ggplot` which calls `config(as_widget(l))`. I cannot tell you more.

**Comment by flying-sheep** [comment]
yes. so what you’re seeing is the plain text representation of a htmlwidget, not an error message:

```r
> class(gg)
[1] "plotly"     "htmlwidget"
> str(IRdisplay::prepare_mimebundle(gg))
List of 2
 $ data    :List of 2
  ..$ text/plain: chr "HTML widgets cannot be represented in plain text (need html)"
  ..$ text/html : chr "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\" />\n<script src=\"data:application/x-javascript;base64,KGZ1bmN0aW9uKCk"| __truncated__
 $ metadata:List of 1
  ..$ text/html:List of 1
  .. ..$ isolated: logi TRUE
```

there’s also a (more useful) HTML representation.

you will only see the plain text representation (which is intended to be helpful) if you e.g. use `jupyter console --kernel=ir` or `jupyter qtconsole --kernel=ir` or `jupyter notebook` with `options(jupyter.display_mimetypes = c('text/plain'))`

if you are using `jupyter notebook` and `'text/html' %in% getOption('jupyter.display_mimetypes')`, you should see the plotly widget.

**Comment by codingbutstillalive** [comment]
Well, I started Jupyter Notebook already with the defaults. When I typed in `'text/html' %in% getOption('jupyter.display_mimetypes')` it returned TRUE, i.e. this option is already set as far as I can see. However, the problem remains.

**Comment by flying-sheep** [comment]
OK, which versions of `IRkernel`, `IRdisplay`, and `repr` do you have?

if they aren’t up-to-date, please update and try again. Also please check what `str(IRdisplay::prepare_mimebundle(gg))` prints.

PS: please start using backticks for code: `` `code` ``

**Comment by codingbutstillalive** [comment]
The latest ones. I installed Jupyter Notebook and latest Python this Monday.

**Comment by flying-sheep** [comment]
and what about `str(IRdisplay::prepare_mimebundle(gg))`?

does it contain `$'text/html'`?

**Comment by anomalosepia** [comment]
anyone figure this out? I'm seeing the same problems. also, when I try: 
`str(IRdisplay::prepare_mimebundle(gg))`

I get 
```
`Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Traceback:

1. str(IRdisplay::prepare_mimebundle(gg))
2. IRdisplay::prepare_mimebundle(gg)
3. filter_map(mimetypes, function(mime) {
 .     tryCatch(withCallingHandlers({
 .         rpr <- mime2repr[[mime]](obj)
 .         if (is.null(rpr)) 
 .             return(NULL)
 .         prepare_content(is.raw(rpr), rpr)
 .     }, error = error_handler), error = outer_handler)
 . })
4. Filter(Negate(is.null), sapply(x, f, simplify = simplify))
5. unlist(lapply(x, f))
6. lapply(x, f)
7. sapply(x, f, simplify = simplify)
8. lapply(X = X, FUN = FUN, ...)
9. FUN(X[[i]], ...)
10. tryCatch(withCallingHandlers({
  .     rpr <- mime2repr[[mime]](obj)
  .     if (is.null(rpr)) 
  .         return(NULL)
  .     prepare_content(is.raw(rpr), rpr)
  . }, error = error_handler), error = outer_handler)
11. tryCatchList(expr, classes, parentenv, handlers)
12. tryCatchOne(expr, names, parentenv, handlers[[1L]])`
```

have reinstalled anaconda on mac os x a few times and no luck. all packages are up to date.

**Comment by Ergodic-Commiter** [comment]
I am getting the same error in Spyder.  ¿Does anyone know a workaround for it?

**Comment by flying-sheep** [comment]
It should work. It works for me with newest everything:

```r
sapply(c('IRkernel', 'IRdisplay', 'repr'), packageVersion)
```

however, i hit this [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1412501)
