### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by asmeurer** [IRkernel/IRdisplay#4]
Can you tag a release? See also https://github.com/IRkernel/IRkernel/issues/60.

**Comment by flying-sheep** [comment]
fixed. i created matching 0.2 tags for you

**Comment by asmeurer** [comment]
The version in the DESCRIPTION doesn't match the version in the tag FYI.

**Comment by flying-sheep** [comment]
since nobody depends on the tag yet, i moved it (i.e. i won’t move tags again since now at least one person – you – depends on it)
