### ISSUE TITLE
using R v.3.5, IRdisplay throws unused argument error ("unused argument (size)")

### ISSUE THREAD

**Issue by pwaltman** [IRkernel/IRdisplay#41]
This is similar to this recent question in this stackoverflow: https://stackoverflow.com/questions/50708887/display-html-report-in-jupyter-with-r

in my case, though, I'm trying to display a png file, and this is the error that I'm getting:
`Error in read(file, size): unused argument (size)
Traceback:

1. IRdisplay::display_png(file = "/home/local/ARCS/pw2470/Pictures/Screenshot_from_2018-05-24_14-26-03.png")
2. display_raw("image/png", TRUE, data, file, img_metadata(width, 
 .     height))
3. prepare_content(isbinary, data, file)
4. read_all(file, isbinary)
`

The weird thing is that this used to work prior to me upgrading to R v.3.5 and re-installing/upgrading everything. is it a compatibility issue with R v.3.5.0 or is there a recent change that broke everything?

**Comment by pwaltman** [comment]
I've found the problem: there's a bug in the utils.r code

The quick fix is to clone the github repo, and make the following edit to the ./IRdisplay/R/utils.r, and on line 38 change the line from:

`read(file,size)`

to

`read(size)`

save the file, switch to the parent directory, and create a new tarbal, e.g.

`tar -zcf IRdisplay.tgz IRdisplay/`

and then re-install your new version, e.g. after re-starting R, type:

`install.packages( "IRdisplay.tgz", repo=NULL )`

**Comment by takluyver** [comment]
@pwaltman thanks, I think that makes sense. Do you want to make a pull request with your change?

**Comment by pwaltman** [comment]
Um, sure. Since I'm not that familiar with github, I tried to open a pull request (clicked on "Pull Requests" tab above, and then clicked the "New Pull Request" button), but all it did was bring me to a page where I could compare changes.

Is it a permissions issue and/or a mistake that I made?

**Comment by takluyver** [comment]
The 'New Pull Request' button works for changes you've already committed. To make the changes through the Github web interface, start from [the file you want to change](https://github.com/IRkernel/IRdisplay/blob/master/R/utils.r), and click the pencil icon to edit it.

The standard way of working on Github if you're contributing to a project regularly is to clone it and make changes locally, then push them to Github. But that's more complicated for a one-off change.

**Comment by pwaltman** [comment]
Ok, thanks for the insx. I just tried to submit the pull request. Let me know if there was a problem with how I did it.

**Comment by flying-sheep** [comment]
thanks for fixing this!

**Comment by jbloom** [comment]
Is there any plan to put the fixed version on CRAN so it can be installed normally? This is a pretty crippling bug for using Jupyter notebooks with R.

**Comment by flying-sheep** [comment]
I’m on it!
