### ISSUE TITLE
Audio player

### ISSUE THREAD

**Issue by psychemedia** [IRkernel/IRdisplay#43]
I'm wondering if there's a recognised way of displaying an audio media player as part of cell output in a Jupyter / IRkernel notebook?

What I'd like to be able to do is something like:

```
display('myFile.wav')
display('myMidi.mid')
display(myAudioObject)
```

There doesn't seem to be a display function for it - is the best route to try to wrap something as an HTMLwidget and then render that?

**Comment by flying-sheep** [comment]
jupyterlab/notebook renders it all so you’d need a renderer that accepts an audio mime type on their side: https://github.com/jupyterlab/jupyterlab/blob/v0.34.7/packages/rendermime/src/factories.ts

and a `repr::repr_html.audio` method on our side (provided the class of the object is “audio”)

so yeah: `shiny::tags$audio(src = 'https://...')` is probably your best bet, as a `repr_html.shiny.tag` exists.

**Comment by psychemedia** [comment]
Ah - thanks... `shiny::tags` looks really handy. 

<s>(The `tags$audio` doesn't seem to work for me atm, though other `tags` constructions do, eg `tags$h1("My header")`, so maybe I'm missing some other bit of setup... Ho hum... rabbit holes..) </s>

Works fine, thanks,  once fully declared, eg:

```
library(shiny)
tags$audio(src = 'test.mp3',  type = "audio/mp3", autoplay = NA, controls = NA)
```

Or without autoplay:

`tags$audio(src = 'test.wav',  type = "audio/wav", controls = NA)`

**Comment by flying-sheep** [comment]
great :smile:
