### ISSUE TITLE
how to view tif file?

### ISSUE THREAD

**Issue by kongdd** [IRkernel/IRdisplay#45]

**Comment by flying-sheep** [comment]
By converting them to a [file format Jupyter supports](https://jupyterlab.readthedocs.io/en/stable/user/file_formats.html#images):

```r
display_png(png::writePNG(tiff::readTIFF("origin.tiff", native=TRUE)))
```

1. `tiff::readTIFF(..., native = TRUE)` returns a `nativeRaster` object
2. `png::writePNG()` takes this and return a `raw()` vector with PNG data
3. `IRdisplay::display_png` takes that and sends it to jupyter.
