### ISSUE TITLE
The output from IRdisplay is not so familiar with that from traditional console

### ISSUE THREAD

**Issue by HuoJnx** [IRkernel/IRdisplay#47]
## Background
This is when I want to use a package called "table1", which outputs an HTML file with its own CSS-style and then automatically activate a page in the browser to show the output.
## When I use the traditional console
![image](https://user-images.githubusercontent.com/40828030/77278157-945cfd00-6cf9-11ea-8ee2-e24e068b027c.png)
>All well when using the traditional console
## When I use the JupyterLab without IRdisplay
![image](https://user-images.githubusercontent.com/40828030/77278295-f0c01c80-6cf9-11ea-93d6-f7d285f52e8b.png)
>It outputs some codes instead of a visualized table.
## When I use the IRdisplay
![image](https://user-images.githubusercontent.com/40828030/77278490-6f1cbe80-6cfa-11ea-86ed-f8845d61d32a.png)
>It shows the table correctly but with the wrong style.
## My problem
Umm... I want to know if there is any method for solving this issue? Because the style of the table is very important for an article that without it, I have to draw it by myself in the WORD.
Or is there any means for me to let the package to activate this own page like that it does in the traditional console?
Thank you very much~~~

**Comment by flying-sheep** [comment]
Easy, you can file an issue with the table1 authors and ask them to implement `repr_html.table1 <- function(obj, ...) unclass(obj)` (and implement it yourself in the meantime)
