### ISSUE TITLE
Can I use display_javascript to replace magic 

### ISSUE THREAD

**Issue by statquant** [IRkernel/IRdisplay#48]
Hello, I wanted to remove autoscrolling in jupiterlab and while I get hundreds of hits in python it seems very complicated to find out how to do it in R.
From [this post](https://stackoverflow.com/questions/36291728/magic-commands-in-r-inside-jupyter) on SO it seems that I should be able to do
`IRdisplay::display_javascript('IPython.OutputArea.auto_scroll_threshold = 99999;')` however when I do this in jupyterlab I get the error : 
`Javascript Error: IPython is not defined
`
Note that this seems to be working in jupyter-notebook
Sorry for the trivial question but I am new to jupyter in R

**Comment by flying-sheep** [comment]
Yeah, in Jupyterlab, this won’t work. Jupyterlab is designed in a way that kernel code can’t execute arbitrary JS: https://github.com/jupyterlab/jupyterlab/issues/4508#issuecomment-385788315

There’s nothing I can do about it, sorry.
