### ISSUE TITLE
row & column sizes centered instead of left-justified

### ISSUE THREAD

**Issue by nick-youngblut** [IRkernel/IRdisplay#49]
At least on Jupyter notebooks with `irkernel` 1.1 and `irdisplay` 0.7, printing a data.frame generated a table with the rows and columns listed in the upper left of the table (eg., `A data.frame 14 x 60`). For example:

![Screen Shot 2021-01-12 at 13 55 13](https://user-images.githubusercontent.com/2468572/104317220-f7fd2480-54dd-11eb-83ae-e63be292c893.png)

However, in Jupyter lab `3.0.3`, the row & column size information is centered in the top-middle of the table. For example:

![Screen Shot 2021-01-12 at 13 56 06](https://user-images.githubusercontent.com/2468572/104317229-fa5f7e80-54dd-11eb-851e-6810653a8f67.png)

...so for tables with many rows, the user must now constantly scroll over just to see the data.frame size. Is there a way to move the row & column size information back to the top left of the table?

**Comment by flying-sheep** [comment]
Sure, you can

1. raise this issue with jupyterlab so they can change their CSS
2. for the time being add some custom CSS like

   ```console
   jupyter labextension install @wallneradam/custom_css
   ```

   And then configure it like:

   ```json
   {
     "rules": [
       {
         "selector": ".jp-OutputArea-output table.dataframe > caption",
         "styles": ["text-align: left"]
       }
     ]
   }
   ```

   (in CSS form:)

   ```css
   .jp-OutputArea-output table.dataframe > caption {
     text-align: left;
   }
   ```
