### ISSUE TITLE
more display_* functions

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRdisplay#5]
Compared to ipython, we are currently missing: 
- display_markdown -> that's interesting because pander, which displays mostly every thing in R in markdown
- display_jpeg -> to complement the *_png and *_svg one?
- display_latex -> also lots of stuff in R which can transform to a latex representation
- display_json -> that's the one I want -> https://github.com/jupyter/jupyter_client/issues/6#issuecomment-94305459 :-) 
- display_pdf -> nice for plotting, which should be included in latex/pdf
- display_javascript -> in python used to implement magics, which influences the behaviour of the notebook... Not sure if we need that...

**Comment by takluyver** [comment]
Note that we don't often use that family of functions in Python code - the normal thing is just to call `display(obj)` and let it pick the best format automatically. So while it makes sense to have them, it's not terribly important, I don't think.

**Comment by flying-sheep** [comment]
like @takluyver said in #3, we currently need a function to display an object by trying to call all `repr_*` stuff on it.

too bad that `display` is already a low level function, as it’s pretty memorable…

**Comment by takluyver** [comment]
I think IRkernel is still young enough that we can rename `IRdisplay::display` if we want to. The equivalent in IPython is `publish_display_data`, I believe, so we could call it something like that. We're also referring to the dicts of mime:data as mimebundles, so we could call it something like `display_mimebundle`.

**Comment by flying-sheep** [comment]
so `display` would take a thing, call all `repr_*` functions defined in a global option or a parameter on it and display the mimebundle resulting from all those that don’t return `NULL`?

the global option could be either a independent option like `jupyter.display_formats`. or we could use the one called `jupyter.result_mimetypes` and already used in the kernel. if we use one, we could rename that one to a more generic name (without “result” in it)

**Comment by jankatins** [comment]
My usecase, why I looked into the missing `display_*` methods was, that I'm currently looking for a way to get json out of the kernel to the client (evaluate code in the context of the kernel and get the returned data structure back). In the end I can probably use a low-level function which gets the mime name and the data, but `display_json(<jsondata_string>, raw=True)` or `display_json(<structure>)`would be nicer :-)

**Comment by jankatins** [comment]
re `display` and what to send: IMO there should only be one knob to tune, so both `display` and the normal "send the returned value" should be based on the same option.

-> Remove `jupyter.plot_mimetypes` and use only `jupyter.result_mimetypes`

**Comment by flying-sheep** [comment]
IPython has multiple knobs as well: [IPython.core.display.set_matplotlib_formats](http://ipython.org/ipython-doc/2/api/generated/IPython.core.display.html#IPython.core.display.set_matplotlib_formats)

**Comment by jankatins** [comment]
But that knob only activates/deactivates image formatter in the list of all formatters (which is the equivalent of `jupyter.result_mimetypes`).

It [more or less does this](https://github.com/ipython/ipython/blob/master/IPython/core/pylabtools.py#L172):

```
new_formats = ... # input...
all_image_formats = ["pdf", "png", "svg", "jpeg"]
assert len(set(new_formats) - set(all_image_formats)) == 0, "got unknown image format"
for fmt in all_image_formats:
   get_formatter(fmt).deactivate()

for fmt in new_formats:
    get_formatter(fmt).deactivate()
```

In IRkernel it would be something like `set_plot_formats(<list of formats>)`, which only touches the image mimetypes and removes all which are not in `list of formats`.

**Comment by takluyver** [comment]
I think an explicit `display()` call and the result of a cell should behave in the same way, with one setting controlling the list of formats they try to generate. Having a separate setting for plots makes sense to me.

**Comment by flying-sheep** [comment]
so @takluyver agrees with me.

plotting is different from displaying totally generic things, so it should be configurable seperably.

so replace `jupyter.result_mimetypes` with `jupyter.display_mimetypes` and use it for `IRdisplay::display()` as well as showing outputs in `IRkernel`, while keeping `jupyter.plot_mimetypes`?

**Comment by jankatins** [comment]
IMO: yes.

**Comment by takluyver** [comment]
Yep, that sounds good. With the caveat that 'use it for IRdisplay::display()' means we'll rename that function as it is to something else, and create a new `IRdisplay::display()` that takes an object and uses `jupyter.result_mimetypes`.

**Comment by flying-sheep** [comment]
yes!
