### ISSUE TITLE
Calling display_html from rpy2 produces flaky segfault error

### ISSUE THREAD

**Issue by matthewgasbarro** [IRkernel/IRdisplay#58]
I am get a segfault error when trying to call display_html from a python environment using rpy2 package. My R notebook is calling a simple a simple python script file that imports rpy2 then imports IRdisplay and then invokes display_html. This is obviously a proof of error script as my use case is calling display_html to render HTML output from a custom python application that I am trying to enable in R. Thanks for any help.

Given:

- Create test_IRdisplay.py file with content:

`from rpy2.robjects.packages import importr
rdisplay = importr('IRdisplay')
rdisplay.display_html('<h1>Hi</h1>')`

- R Packages installed are:
IRkernel 1.2
reticulate 1.22
IRdisplay 1.0

- Python Packages installed are:
rpy2 = "3.4.5"
notebook = "6.4.3"

Steps to Reproduce:

1. Upload test_IRdisplay.py file to Jupyter
2. Open new R notebook in Jupyter 
3. Type `py_run_file("test_IRdisplay.py")`
4. Execute cell repeatedly until Dead Kernel error (for me the error always occurs on the 8th run - 7 successful runs, 8th is an error)

Logs show:
`    *** caught segfault ***
address 0xb8, cause 'memory not mapped'
An irrecoverable exception occurred. R is aborting now ...`

I do see this warning after the firs time the cell is executed from step 4:
`/usr/local/lib/python3.8/site-packages/rpy2/rinterface_lib/embedded.py:134: UserWarning: R was initialized outside of rpy2 (R_NilValue != NULL). Trying to use it nevertheless.
          warnings.warn(`

**Comment by flying-sheep** [comment]
IRkernel contains no compiled code, so any segfaults are the responsibility of rpy2 or R.

I think you need to investigate why that “R was initialized outside of rpy2” warning appears.
