### ISSUE TITLE
Final discussion about design

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRdisplay#6]
#5 totally derailed and IRkernel/IRkernel#97 makes this urgent so let me get this done:

We want the following functions:
1. high level `display` creating a mimebundle by calling all `repr_*` functions on an object, then calling `base_display` on that mimebundle
2. low level `display_mimebundle` and `display1` functions directly accepting mimebundle-like lists
3. high level `display_*` convenience functions for a single object or file.

more questions:
1. should we call `base_display` only with base64 encoded text strings or also with raw vectors and rely on simplejson automatically base64’ing those?
2. i like the `...` API instead of a dedicated list: which should we do:
   - ``` r
     display_mimebundle(list('application/png' = bar,
                             'image/png' = foo),
                        metadata = list(
                             'image/png' = list(width = 400)))
     ```
   - ``` r
     display_mimebundle('application/png' = bar,
                        'image/png' = foo, 
                        metadata = list(
                              'image/png' = list(width = 400)))
     ```
   - ``` r
     display_mimebundle('application/png' = bar,
                        'image/png' = list(foo, width = 400))
     ```
   
   the latter of course would also accept a dedicated `metadata` parameter.

---

change in IRkernel: `jupyter.result_mimetypes` → `jupyter.display_mimetypes`

…which we then use here in the new `display` function to determine which reprs to call

since IRkernel sets the option (if not also set) and this project doesn’t depend on IRkernel: should this project also set a default for that option?

**Comment by jankatins** [comment]
IMO 2.) should be called something like `publish_mimebundle()`, so that it is similar to the one in IPython. I'm not sure what's the difference in purpose for `xxx_mimbundles` and `display1()`

Re your second question (display_mimebundle versions): IMO that's so internal that whatever version you think fits best is good :-)

**Comment by takluyver** [comment]
`publish_mimebundle` makes sense, I've adopted that for #7.

**Comment by flying-sheep** [comment]
added PR #8 building on #3. do we even want those functions in this form?

and what about question 1 (raw vectors)?

**Comment by flying-sheep** [comment]
i really like API#2 and API#3 though.

should we simply support all proposed APIs? it would be as simple as:

``` r
publish_mimebundle <- function(data = NULL, ..., metadata = NULL) {
    if (is.null(data)) data <- list(...)
    # insert code to extract metadata given in the form
    # publish_mimebundle('image/png' = list(data, width = 300))
    base_display(data, metadata)
 }
```

we’re lucky that mime types always contain slashes, so we can add parameters as we like without danger of breaking the named argument API

**Comment by takluyver** [comment]
Not worth it. `publish_mimebundle` is not supposed to be a convenience method, so I'd rather have just one right way to call it.

**Comment by flying-sheep** [comment]
ok. so.
- `display1` → `publish1`?
- raw vectors allowed or no?

**Comment by takluyver** [comment]
Now that we have a good range of `display_foo()` functions, I'd make `display1()` private, and then it doesn't really matter what we call it.

I think that `base_display()` should get the prepared data, with binary stuff base64-encoded. It doesn't seem wise to assume that the JSON encoding will always do what we want with binary data.
